// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as utilities from "../utilities";

// Export members:
export { VersionArgs, VersionResult } from "./version";
export const version: typeof import("./version").version = null as any;
export const versionOutput: typeof import("./version").versionOutput = null as any;
utilities.lazyLoad(exports, ["version","versionOutput"], () => require("./version"));

