// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function version(args?: VersionArgs, opts?: pulumi.InvokeOptions): Promise<VersionResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:api:Version", {
    }, opts);
}

export interface VersionArgs {
}

export interface VersionResult {
    readonly apiBaseUrl: string;
    readonly apiDomain: string;
    readonly apiVersion: string;
    readonly boxModel: string;
    readonly boxModelName: string;
    readonly httpsAvailable: boolean;
    readonly httpsPort: number;
    readonly uid: string;
}
export function versionOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<VersionResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:api:Version", {
    }, opts);
}

