// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { PortForwardingArgs } from "./portForwarding";
export type PortForwarding = import("./portForwarding").PortForwarding;
export const PortForwarding: typeof import("./portForwarding").PortForwarding = null as any;
utilities.lazyLoad(exports, ["PortForwarding"], () => require("./portForwarding"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "freebox:fw:PortForwarding":
                return new PortForwarding(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("freebox", "fw", _module)
