// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class PortForwarding extends pulumi.CustomResource {
    /**
     * Get an existing PortForwarding resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): PortForwarding {
        return new PortForwarding(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:fw:PortForwarding';

    /**
     * Returns true if the given object is an instance of PortForwarding.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is PortForwarding {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === PortForwarding.__pulumiType;
    }

    /**
     * Optional comment for the rule.
     */
    declare public readonly comment: pulumi.Output<string | undefined>;
    /**
     * Whether the forwarding is enabled.
     */
    declare public readonly enabled: pulumi.Output<boolean>;
    /**
     * LAN host information for the target.
     */
    declare public /*out*/ readonly host: pulumi.Output<outputs.LanHost | undefined>;
    /**
     * Hostname reported by the Freebox for this rule.
     */
    declare public /*out*/ readonly hostname: pulumi.Output<string>;
    /**
     * Protocol: tcp or udp.
     */
    declare public readonly ipProtocol: pulumi.Output<string>;
    /**
     * End of the WAN port range (defaults to portRangeStart).
     */
    declare public readonly portRangeEnd: pulumi.Output<number | undefined>;
    /**
     * Start of the WAN port range (inclusive).
     */
    declare public readonly portRangeStart: pulumi.Output<number>;
    /**
     * Freebox API rule ID.
     */
    declare public /*out*/ readonly ruleId: pulumi.Output<number>;
    /**
     * Source IP filter (0.0.0.0 = any).
     */
    declare public readonly sourceIp: pulumi.Output<string | undefined>;
    /**
     * Local IP of the port forwarding target.
     */
    declare public readonly targetIp: pulumi.Output<string>;
    /**
     * Target LAN port (defaults to portRangeStart when range is a single port).
     */
    declare public readonly targetPort: pulumi.Output<number | undefined>;

    /**
     * Create a PortForwarding resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: PortForwardingArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.enabled === undefined && !opts.urn) {
                throw new Error("Missing required property 'enabled'");
            }
            if (args?.ipProtocol === undefined && !opts.urn) {
                throw new Error("Missing required property 'ipProtocol'");
            }
            if (args?.portRangeStart === undefined && !opts.urn) {
                throw new Error("Missing required property 'portRangeStart'");
            }
            if (args?.targetIp === undefined && !opts.urn) {
                throw new Error("Missing required property 'targetIp'");
            }
            resourceInputs["comment"] = args?.comment;
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["ipProtocol"] = args?.ipProtocol;
            resourceInputs["portRangeEnd"] = args?.portRangeEnd;
            resourceInputs["portRangeStart"] = args?.portRangeStart;
            resourceInputs["sourceIp"] = args?.sourceIp;
            resourceInputs["targetIp"] = args?.targetIp;
            resourceInputs["targetPort"] = args?.targetPort;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ruleId"] = undefined /*out*/;
        } else {
            resourceInputs["comment"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["host"] = undefined /*out*/;
            resourceInputs["hostname"] = undefined /*out*/;
            resourceInputs["ipProtocol"] = undefined /*out*/;
            resourceInputs["portRangeEnd"] = undefined /*out*/;
            resourceInputs["portRangeStart"] = undefined /*out*/;
            resourceInputs["ruleId"] = undefined /*out*/;
            resourceInputs["sourceIp"] = undefined /*out*/;
            resourceInputs["targetIp"] = undefined /*out*/;
            resourceInputs["targetPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(PortForwarding.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a PortForwarding resource.
 */
export interface PortForwardingArgs {
    /**
     * Optional comment for the rule.
     */
    comment?: pulumi.Input<string | undefined>;
    /**
     * Whether the forwarding is enabled.
     */
    enabled: pulumi.Input<boolean>;
    /**
     * Protocol: tcp or udp.
     */
    ipProtocol: pulumi.Input<string>;
    /**
     * End of the WAN port range (defaults to portRangeStart).
     */
    portRangeEnd?: pulumi.Input<number | undefined>;
    /**
     * Start of the WAN port range (inclusive).
     */
    portRangeStart: pulumi.Input<number>;
    /**
     * Source IP filter (0.0.0.0 = any).
     */
    sourceIp?: pulumi.Input<string | undefined>;
    /**
     * Local IP of the port forwarding target.
     */
    targetIp: pulumi.Input<string>;
    /**
     * Target LAN port (defaults to portRangeStart when range is a single port).
     */
    targetPort?: pulumi.Input<number | undefined>;
}
