// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getInfo(args?: GetInfoArgs, opts?: pulumi.InvokeOptions): Promise<GetInfoResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:system:getInfo", {
    }, opts);
}

export interface GetInfoArgs {
}

export interface GetInfoResult {
    readonly boardName: string;
    readonly boxAuthenticated: boolean;
    readonly fanRpm: number;
    readonly firmwareVersion: string;
    readonly mac: string;
    readonly serial: string;
    readonly tempCpub: number;
    readonly tempCpum: number;
    readonly tempSw: number;
    readonly uptime: string;
    readonly uptimeVal: number;
    readonly userMainStorage: string;
}
export function getInfoOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInfoResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:system:getInfo", {
    }, opts);
}

