// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

declare var exports: any;
const __config = new pulumi.Config("freebox");

/**
 * The version of the API to use (default: latest).
 */
export declare const apiVersion: string | undefined;
Object.defineProperty(exports, "apiVersion", {
    get() {
        return __config.get("apiVersion");
    },
    enumerable: true,
});

/**
 * The ID of the application for Freebox API authentication.
 */
export declare const appId: string | undefined;
Object.defineProperty(exports, "appId", {
    get() {
        return __config.get("appId");
    },
    enumerable: true,
});

/**
 * The address of the Freebox (default: http://mafreebox.freebox.fr).
 */
export declare const endpoint: string | undefined;
Object.defineProperty(exports, "endpoint", {
    get() {
        return __config.get("endpoint");
    },
    enumerable: true,
});

/**
 * The private token for Freebox API authentication.
 */
export declare const token: string | undefined;
Object.defineProperty(exports, "token", {
    get() {
        return __config.get("token");
    },
    enumerable: true,
});

