// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class File extends pulumi.CustomResource {
    /**
     * Get an existing File resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): File {
        return new File(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:downloads:File';

    /**
     * Returns true if the given object is an instance of File.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is File {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === File.__pulumiType;
    }

    declare public readonly authentication: pulumi.Output<outputs.RemoteFileAuthentication | undefined>;
    /**
     * Checksum of the file on disk.
     */
    declare public readonly checksum: pulumi.Output<string>;
    /**
     * Path on the Freebox where the file will be stored.
     */
    declare public readonly destinationPath: pulumi.Output<string>;
    declare public readonly extract: pulumi.Output<outputs.RemoteFileExtract | undefined>;
    /**
     * Create parent directories if missing.
     */
    declare public readonly parents: pulumi.Output<boolean | undefined>;
    declare public readonly polling: pulumi.Output<outputs.RemoteFilePolling | undefined>;
    /**
     * Size in bytes of the file on disk.
     */
    declare public /*out*/ readonly sizeOnDisk: pulumi.Output<number>;
    /**
     * Inline file content to upload.
     */
    declare public readonly sourceContent: pulumi.Output<string | undefined>;
    /**
     * Path to a local file to upload (relative to the Pulumi engine).
     */
    declare public readonly sourceLocalFile: pulumi.Output<string | undefined>;
    /**
     * Path to an existing file on the Freebox to copy.
     */
    declare public readonly sourceRemoteFile: pulumi.Output<string | undefined>;
    /**
     * URL of the file to download.
     */
    declare public readonly sourceUrl: pulumi.Output<string | undefined>;

    /**
     * Create a File resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: FileArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.destinationPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'destinationPath'");
            }
            resourceInputs["authentication"] = args?.authentication;
            resourceInputs["checksum"] = args?.checksum;
            resourceInputs["destinationPath"] = args?.destinationPath;
            resourceInputs["extract"] = args?.extract;
            resourceInputs["parents"] = args?.parents;
            resourceInputs["polling"] = args?.polling;
            resourceInputs["sourceContent"] = args?.sourceContent;
            resourceInputs["sourceLocalFile"] = args?.sourceLocalFile;
            resourceInputs["sourceRemoteFile"] = args?.sourceRemoteFile;
            resourceInputs["sourceUrl"] = args?.sourceUrl;
            resourceInputs["sizeOnDisk"] = undefined /*out*/;
        } else {
            resourceInputs["authentication"] = undefined /*out*/;
            resourceInputs["checksum"] = undefined /*out*/;
            resourceInputs["destinationPath"] = undefined /*out*/;
            resourceInputs["extract"] = undefined /*out*/;
            resourceInputs["parents"] = undefined /*out*/;
            resourceInputs["polling"] = undefined /*out*/;
            resourceInputs["sizeOnDisk"] = undefined /*out*/;
            resourceInputs["sourceContent"] = undefined /*out*/;
            resourceInputs["sourceLocalFile"] = undefined /*out*/;
            resourceInputs["sourceRemoteFile"] = undefined /*out*/;
            resourceInputs["sourceUrl"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(File.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a File resource.
 */
export interface FileArgs {
    authentication?: pulumi.Input<inputs.RemoteFileAuthenticationArgs | undefined>;
    /**
     * Expected checksum (method:value). Computed after create if omitted.
     */
    checksum?: pulumi.Input<string | undefined>;
    /**
     * Path on the Freebox where the file will be stored.
     */
    destinationPath: pulumi.Input<string>;
    extract?: pulumi.Input<inputs.RemoteFileExtractArgs | undefined>;
    /**
     * Create parent directories if missing.
     */
    parents?: pulumi.Input<boolean | undefined>;
    polling?: pulumi.Input<inputs.RemoteFilePollingArgs | undefined>;
    /**
     * Inline file content to upload.
     */
    sourceContent?: pulumi.Input<string | undefined>;
    /**
     * Path to a local file to upload (relative to the Pulumi engine).
     */
    sourceLocalFile?: pulumi.Input<string | undefined>;
    /**
     * Path to an existing file on the Freebox to copy.
     */
    sourceRemoteFile?: pulumi.Input<string | undefined>;
    /**
     * URL of the file to download.
     */
    sourceUrl?: pulumi.Input<string | undefined>;
}
