// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class Disk extends pulumi.CustomResource {
    /**
     * Get an existing Disk resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Disk {
        return new Disk(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:virtual:Disk';

    /**
     * Returns true if the given object is an instance of Disk.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Disk {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Disk.__pulumiType;
    }

    /**
     * Path to the virtual disk on the Freebox.
     */
    declare public readonly path: pulumi.Output<string>;
    declare public readonly polling: pulumi.Output<outputs.VirtualDiskPolling | undefined>;
    /**
     * Path to an existing disk to copy and resize from.
     */
    declare public readonly resizeFrom: pulumi.Output<string | undefined>;
    /**
     * SHA512 checksum of resizeFrom source (internal).
     */
    declare public /*out*/ readonly resizeFromChecksum: pulumi.Output<string | undefined>;
    /**
     * Space in bytes used on disk.
     */
    declare public /*out*/ readonly sizeOnDisk: pulumi.Output<number>;
    /**
     * Type of virtual disk.
     */
    declare public readonly type: pulumi.Output<string>;
    /**
     * Size in bytes of the virtual disk (as seen inside the VM).
     */
    declare public readonly virtualSize: pulumi.Output<number>;

    /**
     * Create a Disk resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: DiskArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.path === undefined && !opts.urn) {
                throw new Error("Missing required property 'path'");
            }
            if (args?.virtualSize === undefined && !opts.urn) {
                throw new Error("Missing required property 'virtualSize'");
            }
            resourceInputs["path"] = args?.path;
            resourceInputs["polling"] = args?.polling;
            resourceInputs["resizeFrom"] = args?.resizeFrom;
            resourceInputs["type"] = args?.type;
            resourceInputs["virtualSize"] = args?.virtualSize;
            resourceInputs["resizeFromChecksum"] = undefined /*out*/;
            resourceInputs["sizeOnDisk"] = undefined /*out*/;
        } else {
            resourceInputs["path"] = undefined /*out*/;
            resourceInputs["polling"] = undefined /*out*/;
            resourceInputs["resizeFrom"] = undefined /*out*/;
            resourceInputs["resizeFromChecksum"] = undefined /*out*/;
            resourceInputs["sizeOnDisk"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
            resourceInputs["virtualSize"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Disk.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Disk resource.
 */
export interface DiskArgs {
    /**
     * Path to the virtual disk on the Freebox.
     */
    path: pulumi.Input<string>;
    polling?: pulumi.Input<inputs.VirtualDiskPollingArgs | undefined>;
    /**
     * Path to an existing disk to copy and resize from.
     */
    resizeFrom?: pulumi.Input<string | undefined>;
    /**
     * Type of virtual disk (qcow2 or raw). Defaults to qcow2.
     */
    type?: pulumi.Input<string | undefined>;
    /**
     * Size in bytes of the virtual disk (as seen inside the VM).
     */
    virtualSize: pulumi.Input<number>;
}
