// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getDistributions(args?: GetDistributionsArgs, opts?: pulumi.InvokeOptions): Promise<GetDistributionsResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:virtual:getDistributions", {
    }, opts);
}

export interface GetDistributionsArgs {
}

export interface GetDistributionsResult {
    readonly distributions: outputs.VmDistribution[];
}
export function getDistributionsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetDistributionsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:virtual:getDistributions", {
    }, opts);
}

