// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getVirtualDisk(args: GetVirtualDiskArgs, opts?: pulumi.InvokeOptions): Promise<GetVirtualDiskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:virtual:getVirtualDisk", {
        "path": args.path,
    }, opts);
}

export interface GetVirtualDiskArgs {
    path: string;
}

export interface GetVirtualDiskResult {
    readonly actualSize: number;
    readonly path: string;
    readonly type: string;
    readonly virtualSize: number;
}
export function getVirtualDiskOutput(args: GetVirtualDiskOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetVirtualDiskResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:virtual:getVirtualDisk", {
        "path": args.path,
    }, opts);
}

export interface GetVirtualDiskOutputArgs {
    path: pulumi.Input<string>;
}
