// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { DiskArgs } from "./disk";
export type Disk = import("./disk").Disk;
export const Disk: typeof import("./disk").Disk = null as any;
utilities.lazyLoad(exports, ["Disk"], () => require("./disk"));

export { GetDistributionsArgs, GetDistributionsResult } from "./getDistributions";
export const getDistributions: typeof import("./getDistributions").getDistributions = null as any;
export const getDistributionsOutput: typeof import("./getDistributions").getDistributionsOutput = null as any;
utilities.lazyLoad(exports, ["getDistributions","getDistributionsOutput"], () => require("./getDistributions"));

export { GetVirtualDiskArgs, GetVirtualDiskResult, GetVirtualDiskOutputArgs } from "./getVirtualDisk";
export const getVirtualDisk: typeof import("./getVirtualDisk").getVirtualDisk = null as any;
export const getVirtualDiskOutput: typeof import("./getVirtualDisk").getVirtualDiskOutput = null as any;
utilities.lazyLoad(exports, ["getVirtualDisk","getVirtualDiskOutput"], () => require("./getVirtualDisk"));

export { MachineArgs } from "./machine";
export type Machine = import("./machine").Machine;
export const Machine: typeof import("./machine").Machine = null as any;
utilities.lazyLoad(exports, ["Machine"], () => require("./machine"));

export { MachinePowerArgs } from "./machinePower";
export type MachinePower = import("./machinePower").MachinePower;
export const MachinePower: typeof import("./machinePower").MachinePower = null as any;
utilities.lazyLoad(exports, ["MachinePower"], () => require("./machinePower"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "freebox:virtual:Disk":
                return new Disk(name, <any>undefined, { urn })
            case "freebox:virtual:Machine":
                return new Machine(name, <any>undefined, { urn })
            case "freebox:virtual:MachinePower":
                return new MachinePower(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("freebox", "virtual", _module)
