// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class Machine extends pulumi.CustomResource {
    /**
     * Get an existing Machine resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Machine {
        return new Machine(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:virtual:Machine';

    /**
     * Returns true if the given object is an instance of Machine.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Machine {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Machine.__pulumiType;
    }

    /**
     * USB ports to bind.
     */
    declare public readonly bindUsbPorts: pulumi.Output<string[] | undefined>;
    /**
     * Path to CD/ISO image.
     */
    declare public readonly cdPath: pulumi.Output<string | undefined>;
    /**
     * Cloud-init hostname.
     */
    declare public readonly cloudinitHostname: pulumi.Output<string | undefined>;
    /**
     * Cloud-init user-data.
     */
    declare public readonly cloudinitUserdata: pulumi.Output<string | undefined>;
    /**
     * Path to the disk image.
     */
    declare public readonly diskPath: pulumi.Output<string>;
    /**
     * Disk type: qcow2 or raw.
     */
    declare public readonly diskType: pulumi.Output<string>;
    /**
     * Enable cloud-init.
     */
    declare public readonly enableCloudinit: pulumi.Output<boolean | undefined>;
    /**
     * Enable VNC screen.
     */
    declare public readonly enableScreen: pulumi.Output<boolean | undefined>;
    /**
     * First IPv4 address of the VM on the LAN (when running).
     */
    declare public /*out*/ readonly ipv4: pulumi.Output<string | undefined>;
    /**
     * MAC address of the VM.
     */
    declare public /*out*/ readonly mac: pulumi.Output<string>;
    /**
     * Memory in MB.
     */
    declare public readonly memory: pulumi.Output<number>;
    /**
     * Name of the VM.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * Network binds (interface, IPv4, IPv6) for the VM.
     */
    declare public /*out*/ readonly networking: pulumi.Output<outputs.NetworkingBind[] | undefined>;
    /**
     * OS type (for icon).
     */
    declare public readonly os: pulumi.Output<string | undefined>;
    /**
     * Current VM status (running/stopped).
     */
    declare public readonly status: pulumi.Output<string>;
    /**
     * Operation timeouts (create, update, read, delete, kill, networking).
     */
    declare public readonly timeouts: pulumi.Output<outputs.VirtualMachineTimeouts | undefined>;
    /**
     * Number of vCPUs.
     */
    declare public readonly vcpus: pulumi.Output<number>;
    /**
     * Freebox API VM ID.
     */
    declare public /*out*/ readonly vmId: pulumi.Output<number>;

    /**
     * Create a Machine resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MachineArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.diskPath === undefined && !opts.urn) {
                throw new Error("Missing required property 'diskPath'");
            }
            if (args?.diskType === undefined && !opts.urn) {
                throw new Error("Missing required property 'diskType'");
            }
            if (args?.memory === undefined && !opts.urn) {
                throw new Error("Missing required property 'memory'");
            }
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.vcpus === undefined && !opts.urn) {
                throw new Error("Missing required property 'vcpus'");
            }
            resourceInputs["bindUsbPorts"] = args?.bindUsbPorts;
            resourceInputs["cdPath"] = args?.cdPath;
            resourceInputs["cloudinitHostname"] = args?.cloudinitHostname;
            resourceInputs["cloudinitUserdata"] = args?.cloudinitUserdata;
            resourceInputs["diskPath"] = args?.diskPath;
            resourceInputs["diskType"] = args?.diskType;
            resourceInputs["enableCloudinit"] = args?.enableCloudinit;
            resourceInputs["enableScreen"] = args?.enableScreen;
            resourceInputs["memory"] = args?.memory;
            resourceInputs["name"] = args?.name;
            resourceInputs["os"] = args?.os;
            resourceInputs["status"] = args?.status;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["vcpus"] = args?.vcpus;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["mac"] = undefined /*out*/;
            resourceInputs["networking"] = undefined /*out*/;
            resourceInputs["vmId"] = undefined /*out*/;
        } else {
            resourceInputs["bindUsbPorts"] = undefined /*out*/;
            resourceInputs["cdPath"] = undefined /*out*/;
            resourceInputs["cloudinitHostname"] = undefined /*out*/;
            resourceInputs["cloudinitUserdata"] = undefined /*out*/;
            resourceInputs["diskPath"] = undefined /*out*/;
            resourceInputs["diskType"] = undefined /*out*/;
            resourceInputs["enableCloudinit"] = undefined /*out*/;
            resourceInputs["enableScreen"] = undefined /*out*/;
            resourceInputs["ipv4"] = undefined /*out*/;
            resourceInputs["mac"] = undefined /*out*/;
            resourceInputs["memory"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["networking"] = undefined /*out*/;
            resourceInputs["os"] = undefined /*out*/;
            resourceInputs["status"] = undefined /*out*/;
            resourceInputs["timeouts"] = undefined /*out*/;
            resourceInputs["vcpus"] = undefined /*out*/;
            resourceInputs["vmId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Machine.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Machine resource.
 */
export interface MachineArgs {
    /**
     * USB ports to bind.
     */
    bindUsbPorts?: pulumi.Input<pulumi.Input<string>[] | undefined>;
    /**
     * Path to CD/ISO image.
     */
    cdPath?: pulumi.Input<string | undefined>;
    /**
     * Cloud-init hostname.
     */
    cloudinitHostname?: pulumi.Input<string | undefined>;
    /**
     * Cloud-init user-data.
     */
    cloudinitUserdata?: pulumi.Input<string | undefined>;
    /**
     * Path to the disk image.
     */
    diskPath: pulumi.Input<string>;
    /**
     * Disk type: qcow2 or raw.
     */
    diskType: pulumi.Input<string>;
    /**
     * Enable cloud-init.
     */
    enableCloudinit?: pulumi.Input<boolean | undefined>;
    /**
     * Enable VNC screen.
     */
    enableScreen?: pulumi.Input<boolean | undefined>;
    /**
     * Memory in MB.
     */
    memory: pulumi.Input<number>;
    /**
     * Name of the VM.
     */
    name: pulumi.Input<string>;
    /**
     * OS type (for icon).
     */
    os?: pulumi.Input<string | undefined>;
    /**
     * Desired state: running or stopped. Default running.
     */
    status?: pulumi.Input<string | undefined>;
    /**
     * Operation timeouts (create, update, read, delete, kill, networking).
     */
    timeouts?: pulumi.Input<inputs.VirtualMachineTimeoutsArgs | undefined>;
    /**
     * Number of vCPUs.
     */
    vcpus: pulumi.Input<number>;
}
