// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export class MachinePower extends pulumi.CustomResource {
    /**
     * Get an existing MachinePower resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): MachinePower {
        return new MachinePower(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:virtual:MachinePower';

    /**
     * Returns true if the given object is an instance of MachinePower.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is MachinePower {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === MachinePower.__pulumiType;
    }

    /**
     * Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
     */
    declare public readonly killTimeout: pulumi.Output<number | undefined>;
    /**
     * Desired power state: running or stopped.
     */
    declare public readonly powerState: pulumi.Output<string>;
    /**
     * Timeouts for power operations.
     */
    declare public readonly timeouts: pulumi.Output<outputs.VirtualMachinePowerTimeouts | undefined>;
    /**
     * Identifier of the virtual machine.
     */
    declare public readonly vmId: pulumi.Output<number>;

    /**
     * Create a MachinePower resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: MachinePowerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.powerState === undefined && !opts.urn) {
                throw new Error("Missing required property 'powerState'");
            }
            if (args?.vmId === undefined && !opts.urn) {
                throw new Error("Missing required property 'vmId'");
            }
            resourceInputs["killTimeout"] = args?.killTimeout;
            resourceInputs["powerState"] = args?.powerState;
            resourceInputs["timeouts"] = args?.timeouts;
            resourceInputs["vmId"] = args?.vmId;
        } else {
            resourceInputs["killTimeout"] = undefined /*out*/;
            resourceInputs["powerState"] = undefined /*out*/;
            resourceInputs["timeouts"] = undefined /*out*/;
            resourceInputs["vmId"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(MachinePower.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a MachinePower resource.
 */
export interface MachinePowerArgs {
    /**
     * Seconds to wait for graceful shutdown before force kill (default 30). Deprecated: use timeouts.kill.
     */
    killTimeout?: pulumi.Input<number | undefined>;
    /**
     * Desired power state: running or stopped.
     */
    powerState: pulumi.Input<string>;
    /**
     * Timeouts for power operations.
     */
    timeouts?: pulumi.Input<inputs.VirtualMachinePowerTimeoutsArgs | undefined>;
    /**
     * Identifier of the virtual machine.
     */
    vmId: pulumi.Input<number>;
}
