// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Config extends pulumi.CustomResource {
    /**
     * Get an existing Config resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Config {
        return new Config(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:lan:Config';

    /**
     * Returns true if the given object is an instance of Config.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Config {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Config.__pulumiType;
    }

    declare public readonly ip: pulumi.Output<string | undefined>;
    declare public readonly mode: pulumi.Output<string | undefined>;
    declare public readonly name: pulumi.Output<string | undefined>;
    declare public readonly nameDns: pulumi.Output<string | undefined>;
    declare public readonly nameMdns: pulumi.Output<string | undefined>;
    declare public readonly nameNetbios: pulumi.Output<string | undefined>;

    /**
     * Create a Config resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ConfigArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["ip"] = args?.ip;
            resourceInputs["mode"] = args?.mode;
            resourceInputs["name"] = args?.name;
            resourceInputs["nameDns"] = args?.nameDns;
            resourceInputs["nameMdns"] = args?.nameMdns;
            resourceInputs["nameNetbios"] = args?.nameNetbios;
        } else {
            resourceInputs["ip"] = undefined /*out*/;
            resourceInputs["mode"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["nameDns"] = undefined /*out*/;
            resourceInputs["nameMdns"] = undefined /*out*/;
            resourceInputs["nameNetbios"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Config.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Config resource.
 */
export interface ConfigArgs {
    ip?: pulumi.Input<string | undefined>;
    mode?: pulumi.Input<string | undefined>;
    name?: pulumi.Input<string | undefined>;
    nameDns?: pulumi.Input<string | undefined>;
    nameMdns?: pulumi.Input<string | undefined>;
    nameNetbios?: pulumi.Input<string | undefined>;
}
