// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getConfig(args?: GetConfigArgs, opts?: pulumi.InvokeOptions): Promise<GetConfigResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:lan:getConfig", {
    }, opts);
}

export interface GetConfigArgs {
}

export interface GetConfigResult {
    readonly ip: string;
    readonly mode: string;
    readonly name: string;
    readonly nameDns: string;
    readonly nameMdns: string;
    readonly nameNetbios: string;
}
export function getConfigOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetConfigResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:lan:getConfig", {
    }, opts);
}

