// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getInterfaces(args?: GetInterfacesArgs, opts?: pulumi.InvokeOptions): Promise<GetInterfacesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:lan:getInterfaces", {
    }, opts);
}

export interface GetInterfacesArgs {
}

export interface GetInterfacesResult {
    readonly interfaces: outputs.LanInterfaceInfo[];
}
export function getInterfacesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInterfacesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:lan:getInterfaces", {
    }, opts);
}

