// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getInterfaceHosts(args: GetInterfaceHostsArgs, opts?: pulumi.InvokeOptions): Promise<GetInterfaceHostsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:lan:getInterfaceHosts", {
        "interface": args.interface,
    }, opts);
}

export interface GetInterfaceHostsArgs {
    interface: string;
}

export interface GetInterfaceHostsResult {
    readonly hosts: outputs.LanInterfaceHostRef[];
}
export function getInterfaceHostsOutput(args: GetInterfaceHostsOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInterfaceHostsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:lan:getInterfaceHosts", {
        "interface": args.interface,
    }, opts);
}

export interface GetInterfaceHostsOutputArgs {
    interface: pulumi.Input<string>;
}
