// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getInterfaceHost(args: GetInterfaceHostArgs, opts?: pulumi.InvokeOptions): Promise<GetInterfaceHostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:lan:getInterfaceHost", {
        "hostId": args.hostId,
        "interface": args.interface,
    }, opts);
}

export interface GetInterfaceHostArgs {
    hostId: string;
    interface: string;
}

export interface GetInterfaceHostResult {
    readonly hostId: string;
    readonly interface: string;
    readonly l2ident: outputs.LanHostL2Ident;
}
export function getInterfaceHostOutput(args: GetInterfaceHostOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetInterfaceHostResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:lan:getInterfaceHost", {
        "hostId": args.hostId,
        "interface": args.interface,
    }, opts);
}

export interface GetInterfaceHostOutputArgs {
    hostId: pulumi.Input<string>;
    interface: pulumi.Input<string>;
}
