// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { ConfigArgs } from "./config";
export type Config = import("./config").Config;
export const Config: typeof import("./config").Config = null as any;
utilities.lazyLoad(exports, ["Config"], () => require("./config"));

export { GetConfigArgs, GetConfigResult } from "./getConfig";
export const getConfig: typeof import("./getConfig").getConfig = null as any;
export const getConfigOutput: typeof import("./getConfig").getConfigOutput = null as any;
utilities.lazyLoad(exports, ["getConfig","getConfigOutput"], () => require("./getConfig"));

export { GetInterfaceHostArgs, GetInterfaceHostResult, GetInterfaceHostOutputArgs } from "./getInterfaceHost";
export const getInterfaceHost: typeof import("./getInterfaceHost").getInterfaceHost = null as any;
export const getInterfaceHostOutput: typeof import("./getInterfaceHost").getInterfaceHostOutput = null as any;
utilities.lazyLoad(exports, ["getInterfaceHost","getInterfaceHostOutput"], () => require("./getInterfaceHost"));

export { GetInterfaceHostsArgs, GetInterfaceHostsResult, GetInterfaceHostsOutputArgs } from "./getInterfaceHosts";
export const getInterfaceHosts: typeof import("./getInterfaceHosts").getInterfaceHosts = null as any;
export const getInterfaceHostsOutput: typeof import("./getInterfaceHosts").getInterfaceHostsOutput = null as any;
utilities.lazyLoad(exports, ["getInterfaceHosts","getInterfaceHostsOutput"], () => require("./getInterfaceHosts"));

export { GetInterfacesArgs, GetInterfacesResult } from "./getInterfaces";
export const getInterfaces: typeof import("./getInterfaces").getInterfaces = null as any;
export const getInterfacesOutput: typeof import("./getInterfaces").getInterfacesOutput = null as any;
utilities.lazyLoad(exports, ["getInterfaces","getInterfacesOutput"], () => require("./getInterfaces"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "freebox:lan:Config":
                return new Config(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("freebox", "lan", _module)
