// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as utilities from "../utilities";

export function getLeases(args?: GetLeasesArgs, opts?: pulumi.InvokeOptions): Promise<GetLeasesResult> {
    args = args || {};
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:dhcp:getLeases", {
    }, opts);
}

export interface GetLeasesArgs {
}

export interface GetLeasesResult {
    readonly leases: outputs.DhcpLeaseInfo[];
}
export function getLeasesOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLeasesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:dhcp:getLeases", {
    }, opts);
}

