// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export function getLease(args: GetLeaseArgs, opts?: pulumi.InvokeOptions): Promise<GetLeaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("freebox:dhcp:getLease", {
        "mac": args.mac,
    }, opts);
}

export interface GetLeaseArgs {
    mac: string;
}

export interface GetLeaseResult {
    readonly comment: string;
    readonly hostname: string;
    readonly ip: string;
    readonly leaseId: string;
    readonly mac: string;
}
export function getLeaseOutput(args: GetLeaseOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetLeaseResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("freebox:dhcp:getLease", {
        "mac": args.mac,
    }, opts);
}

export interface GetLeaseOutputArgs {
    mac: pulumi.Input<string>;
}
