// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { GetLeaseArgs, GetLeaseResult, GetLeaseOutputArgs } from "./getLease";
export const getLease: typeof import("./getLease").getLease = null as any;
export const getLeaseOutput: typeof import("./getLease").getLeaseOutput = null as any;
utilities.lazyLoad(exports, ["getLease","getLeaseOutput"], () => require("./getLease"));

export { GetLeasesArgs, GetLeasesResult } from "./getLeases";
export const getLeases: typeof import("./getLeases").getLeases = null as any;
export const getLeasesOutput: typeof import("./getLeases").getLeasesOutput = null as any;
utilities.lazyLoad(exports, ["getLeases","getLeasesOutput"], () => require("./getLeases"));

export { StaticLeaseArgs } from "./staticLease";
export type StaticLease = import("./staticLease").StaticLease;
export const StaticLease: typeof import("./staticLease").StaticLease = null as any;
utilities.lazyLoad(exports, ["StaticLease"], () => require("./staticLease"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "freebox:dhcp:StaticLease":
                return new StaticLease(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("freebox", "dhcp", _module)
