// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface PollingSpecArgs {
    interval?: pulumi.Input<number | undefined>;
    timeout?: pulumi.Input<number | undefined>;
}

export interface RemoteFileAuthenticationArgs {
    basicAuth?: pulumi.Input<inputs.RemoteFileBasicAuthArgs | undefined>;
}

export interface RemoteFileBasicAuthArgs {
    password?: pulumi.Input<string | undefined>;
    username?: pulumi.Input<string | undefined>;
}

export interface RemoteFileExtractArgs {
    destinationPath?: pulumi.Input<string | undefined>;
    overwrite?: pulumi.Input<boolean | undefined>;
    password?: pulumi.Input<string | undefined>;
}

export interface RemoteFilePollingArgs {
    checksumCompute?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    copy?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    delete?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    download?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    extract?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    move?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    upload?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
}

export interface VirtualDiskPollingArgs {
    checksum?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    copy?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    create?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    delete?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    move?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
    resize?: pulumi.Input<inputs.PollingSpecArgs | undefined>;
}

export interface VirtualMachinePowerTimeoutsArgs {
    kill?: pulumi.Input<number | undefined>;
}

export interface VirtualMachineTimeoutsArgs {
    create?: pulumi.Input<number | undefined>;
    delete?: pulumi.Input<number | undefined>;
    kill?: pulumi.Input<number | undefined>;
    networking?: pulumi.Input<number | undefined>;
    read?: pulumi.Input<number | undefined>;
    update?: pulumi.Input<number | undefined>;
}

