// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DhcpLeaseInfo {
    comment: string;
    hostname: string;
    ip: string;
    leaseId: string;
    mac: string;
}

export interface LanHost {
    active: boolean;
    defaultName: string;
    firstActivitySeconds?: number;
    hostId: string;
    hostType: string;
    interface: string;
    l2ident: outputs.LanHostL2Ident;
    l3connectivities: outputs.LanHostL3Connectivity[];
    names: outputs.LanHostName[];
    networkControl?: outputs.LanHostNetworkControl;
    persistent: boolean;
    primaryName: string;
    primaryNameManual: boolean;
    reachable: boolean;
    vendorName: string;
}

export interface LanHostL2Ident {
    l2Id: string;
    type: string;
}

export interface LanHostL3Connectivity {
    active: boolean;
    address: string;
    reachable: boolean;
    type: string;
}

export interface LanHostName {
    name: string;
    source: string;
}

export interface LanHostNetworkControl {
    currentMode: string;
    name: string;
    profileId: number;
}

export interface LanInterfaceHostRef {
    hostId: string;
    interface: string;
    l2ident: outputs.LanHostL2Ident;
}

export interface LanInterfaceInfo {
    hostCount: number;
    name: string;
}

export interface NetworkingBind {
    interface: string;
    ipv4: string;
    ipv6?: string[];
}

export interface PollingSpec {
    interval?: number;
    timeout?: number;
}

export interface RemoteFileAuthentication {
    basicAuth?: outputs.RemoteFileBasicAuth;
}

export interface RemoteFileBasicAuth {
    password?: string;
    username?: string;
}

export interface RemoteFileExtract {
    destinationPath?: string;
    overwrite?: boolean;
    password?: string;
}

export interface RemoteFilePolling {
    checksumCompute?: outputs.PollingSpec;
    copy?: outputs.PollingSpec;
    delete?: outputs.PollingSpec;
    download?: outputs.PollingSpec;
    extract?: outputs.PollingSpec;
    move?: outputs.PollingSpec;
    upload?: outputs.PollingSpec;
}

export interface VirtualDiskPolling {
    checksum?: outputs.PollingSpec;
    copy?: outputs.PollingSpec;
    create?: outputs.PollingSpec;
    delete?: outputs.PollingSpec;
    move?: outputs.PollingSpec;
    resize?: outputs.PollingSpec;
}

export interface VirtualMachinePowerTimeouts {
    kill?: number;
}

export interface VirtualMachineTimeouts {
    create?: number;
    delete?: number;
    kill?: number;
    networking?: number;
    read?: number;
    update?: number;
}

export interface VmDistribution {
    hash: string;
    name: string;
    os: string;
    url: string;
}

