// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

export class Server extends pulumi.CustomResource {
    /**
     * Get an existing Server resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Server {
        return new Server(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'freebox:vpn:Server';

    /**
     * Returns true if the given object is an instance of Server.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Server {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Server.__pulumiType;
    }

    declare public /*out*/ readonly ca: pulumi.Output<string>;
    declare public readonly enabled: pulumi.Output<boolean | undefined>;
    declare public readonly pushDhcp: pulumi.Output<boolean | undefined>;
    declare public readonly serverIp: pulumi.Output<string | undefined>;
    declare public readonly serverMask: pulumi.Output<string | undefined>;
    declare public readonly serverPort: pulumi.Output<number | undefined>;

    /**
     * Create a Server resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: ServerArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            resourceInputs["enabled"] = args?.enabled;
            resourceInputs["pushDhcp"] = args?.pushDhcp;
            resourceInputs["serverIp"] = args?.serverIp;
            resourceInputs["serverMask"] = args?.serverMask;
            resourceInputs["serverPort"] = args?.serverPort;
            resourceInputs["ca"] = undefined /*out*/;
        } else {
            resourceInputs["ca"] = undefined /*out*/;
            resourceInputs["enabled"] = undefined /*out*/;
            resourceInputs["pushDhcp"] = undefined /*out*/;
            resourceInputs["serverIp"] = undefined /*out*/;
            resourceInputs["serverMask"] = undefined /*out*/;
            resourceInputs["serverPort"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Server.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Server resource.
 */
export interface ServerArgs {
    enabled?: pulumi.Input<boolean | undefined>;
    pushDhcp?: pulumi.Input<boolean | undefined>;
    serverIp?: pulumi.Input<string | undefined>;
    serverMask?: pulumi.Input<string | undefined>;
    serverPort?: pulumi.Input<number | undefined>;
}
