// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));


// Export sub-modules:
import * as api from "./api";
import * as config from "./config";
import * as dhcp from "./dhcp";
import * as downloads from "./downloads";
import * as fw from "./fw";
import * as lan from "./lan";
import * as system from "./system";
import * as types from "./types";
import * as virtual from "./virtual";
import * as vpn from "./vpn";

export {
    api,
    config,
    dhcp,
    downloads,
    fw,
    lan,
    system,
    types,
    virtual,
    vpn,
};
pulumi.runtime.registerResourcePackage("freebox", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:freebox") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
