// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * Configuration for the Freebox provider.
 */
export class Provider extends pulumi.ProviderResource {
    /** @internal */
    public static readonly __pulumiType = 'freebox';

    /**
     * Returns true if the given object is an instance of Provider.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Provider {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === "pulumi:providers:" + Provider.__pulumiType;
    }

    /**
     * The version of the API to use (default: latest).
     */
    declare public readonly apiVersion: pulumi.Output<string | undefined>;
    /**
     * The ID of the application for Freebox API authentication.
     */
    declare public readonly appId: pulumi.Output<string>;
    /**
     * The address of the Freebox (default: http://mafreebox.freebox.fr).
     */
    declare public readonly endpoint: pulumi.Output<string | undefined>;
    /**
     * The private token for Freebox API authentication.
     */
    declare public readonly token: pulumi.Output<string>;

    /**
     * Create a Provider resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ProviderArgs, opts?: pulumi.ResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        {
            if (args?.appId === undefined && !opts.urn) {
                throw new Error("Missing required property 'appId'");
            }
            if (args?.token === undefined && !opts.urn) {
                throw new Error("Missing required property 'token'");
            }
            resourceInputs["apiVersion"] = args?.apiVersion;
            resourceInputs["appId"] = args?.appId ? pulumi.secret(args.appId) : undefined;
            resourceInputs["endpoint"] = args?.endpoint;
            resourceInputs["token"] = args?.token ? pulumi.secret(args.token) : undefined;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const secretOpts = { additionalSecretOutputs: ["appId", "token"] };
        opts = pulumi.mergeOptions(opts, secretOpts);
        super(Provider.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Provider resource.
 */
export interface ProviderArgs {
    /**
     * The version of the API to use (default: latest).
     */
    apiVersion?: pulumi.Input<string | undefined>;
    /**
     * The ID of the application for Freebox API authentication.
     */
    appId: pulumi.Input<string>;
    /**
     * The address of the Freebox (default: http://mafreebox.freebox.fr).
     */
    endpoint?: pulumi.Input<string | undefined>;
    /**
     * The private token for Freebox API authentication.
     */
    token: pulumi.Input<string>;
}
